### ISSUE TITLE
Add support to Configure Account Policies

### ISSUE THREAD

**Issue by gaelcolas** [ChrisAWalker/cSecurityOptions#6]
Hi,
First of all, thanks for those DSC resources!
Am I correct that it is not currently possible to configure the Account policies and Account Lockout polcies?

i.e.

```
PasswordHistorySize
MaximumPasswordAge
MinimumPasswordAge
MinimumPasswordLength
PasswordComplexity
ClearTextPassword

ResetLockoutCount
LockoutBadCount
LockoutDuration
```

![image](https://cloud.githubusercontent.com/assets/8962101/18779975/4553c90c-8173-11e6-80f1-e7e9764dc599.png)

Using SecEdit, those are at the top of the file:

```
[Unicode]
Unicode=yes
[System Access]
MinimumPasswordAge = 0
MaximumPasswordAge = 42
MinimumPasswordLength = 0
PasswordComplexity = 1
PasswordHistorySize = 0
LockoutBadCount = 0
RequireLogonToChangePassword = 0
ForceLogoffWhenHourExpire = 0
NewAdministratorName = "Administrator"
NewGuestName = "Guest"
ClearTextPassword = 0
LSAAnonymousNameLookup = 0
EnableAdminAccount = 1
EnableGuestAccount = 0
```

**Comment by ChrisAWalker** [comment]
If you look at the source code within the powershell, you will see that all
these options are offered to be managed.

The PowerShell code is leveraging SecEdit to modify this policy.

**Comment by gaelcolas** [comment]
Oh you're right, I found it in AccountAndBasicAuditing.
Apologies, I got confused with the commented out part in LSA_SecurityOptions.
